### ISSUE TITLE
Using tpm2-pkcs11 with GnuTLS p11tool and certtool

### ISSUE THREAD

**Issue by stefanberger** [tpm2-software/tpm2-pkcs11#44]
I have been trying to get  tpm2-pkcs11 to work with GnuTLS's `p11tool`, but haven't been successful. Do you happen to have some steps for how to create a TPM 2 key with your tools or `p11tool` (better) and use the key with the `p11tool` then? Maybe something is wrong with my setup.

I also posted a message with the other PKCS11 TPM 2 module that I couldn't get to work, either: https://github.com/irtimmer/tpm2-pk11/issues/84

**Comment by dwmw2** [comment]
I think it's fixed to install the p11-kit .module file now so that it's actually seen by applications:
```
$ p11-kit list-modules
p11-kit-trust: p11-kit-trust.so
    library-description: PKCS#11 Kit Trust Module
    library-manufacturer: PKCS#11 Kit
    library-version: 0.23
    token: System Trust
        manufacturer: PKCS#11 Kit
        model: p11-kit-trust
        serial-number: 1
        hardware-version: 0.23
        flags:
               write-protected
               token-initialized
tpm2-pkcs11: tpm2-pkcs11.so
    library-description:  TPM2.0 Cryptoki
    library-manufacturer:  Intel
    library-version: 42.42
    token: label
        manufacturer: Intel
        model: TPM2 PKCS#11
        serial-number: 0000000000000000
        flags:
               rng
               login-required
               token-initialized
```

However, there are still locking issues:
```
$ p11tool --list-tokens
Token 0:
	URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
	Label: System Trust
	Type: Trust module
	Manufacturer: PKCS#11 Kit
	Model: p11-kit-trust
	Serial: 1
	Module: p11-kit-trust.so


ERROR: Could not lock mutex: Resource deadlock avoided
p11tool: src/lib/mutex.h:70: mutex_lock_fatal: Assertion `rv == CKR_OK' failed.
Aborted
```
```

**Comment by dwmw2** [comment]
Which is probably https://github.com/tpm2-software/tpm2-pkcs11/issues/38 ?

**Comment by stefanberger** [comment]
I don't seem to have this locking issue at least...

```
# p11-kit list-modules
p11-kit-trust: p11-kit-trust.so
    library-description: PKCS#11 Kit Trust Module
    library-manufacturer: PKCS#11 Kit
    library-version: 0.23
    token: System Trust
        manufacturer: PKCS#11 Kit
        model: p11-kit-trust
        serial-number: 1
        hardware-version: 0.23
        flags:
               token-initialized
    token: Default Trust
        manufacturer: PKCS#11 Kit
        model: p11-kit-trust
        serial-number: 1
        hardware-version: 0.23
        flags:
               write-protected
               token-initialized
opensc: opensc-pkcs11.so
    library-description: OpenSC smartcard framework
    library-manufacturer: OpenSC Project
    library-version: 0.18
tpm2_pkcs11: libtpm2_pkcs11.so
    library-description:  TPM2.0 Cryptoki
    library-manufacturer:  Intel
    library-version: 42.42
# p11tool --list-tokens
Token 0:
	URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
	Label: System Trust
	Type: Trust module
	Flags: uPIN uninitialized
	Manufacturer: PKCS#11 Kit
	Model: p11-kit-trust
	Serial: 1
	Module: p11-kit-trust.so


Token 1:
	URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
	Label: Default Trust
	Type: Trust module
	Flags: uPIN uninitialized
	Manufacturer: PKCS#11 Kit
	Model: p11-kit-trust
	Serial: 1
	Module: p11-kit-trust.so
```
