### ISSUE TITLE
TPM Parameter Value out of Range or Incorrect Error

### ISSUE THREAD

**Issue by heobu** [tpm2-software/tpm2-pkcs11#628]
Hello,

I am trying to create keypairs but I keep getting this error for RSA keypair generation using the C_GenerateKeyPair function. I've already had some problems creating EC keys, but at least I was able to create RSA ones, now this is not working either.

This is the error I am getting:

![image](https://user-images.githubusercontent.com/22464721/99633950-c709f180-2a50-11eb-8195-d89202b5db35.png)

I also get a similar error now when I try to list existing keypairs as follows:

![image](https://user-images.githubusercontent.com/22464721/99634153-0cc6ba00-2a51-11eb-91f0-edace97c0ae5.png)

This also used to work, but now it's failing.

My openssl version: 1.0.2r

I also have tpm2-tss and tpm2-tools installed in this environment.

**Comment by williamcroberts** [comment]
What version of tpm2-tss and tpm2-tools, and tpm2-pkcs11 do you have installed?

You're issue seems related to the one that @PeterHuewe describes here:
  - https://github.com/tpm2-software/tpm2-pkcs11/issues/134

If that premise is correct, It looks like it was fixed in tpm2-tss project as PR:
  - https://github.com/tpm2-software/tpm2-tss/pull/1275

It was merged as commit:
  - https://github.com/tpm2-software/tpm2-tss/commit/ed92b832b85d94744e2d713473d560c22647015b

Which seems to be on tpm2-tss versions >= 2.3.0:
```bash
git tag --contains ed92b832b85d94744e2d713473d560c22647015b
2.3.0
2.3.0
2.3.0-rc0
2.3.1
2.3.1-rc0
2.3.2
2.3.2-rc0
2.3.3
2.4.0
2.4.0-rc2
2.4.1
2.4.1-rc0
2.4.1-rc1
2.4.2
2.4.2-rc1
2.4.2-rc2
2.4.3
2.4.3-rc0
3.0.0
3.0.0-rc0
3.0.0-rc1
3.0.1
```

FAPI didn't get introduced until version 2.4.0, so I would imagine that you should have this patch. So I am perplexed at the exact issue that is happening. By any chance do you have an older ESAPI and newer FAPI installed in such a way where you're not linking against the ESYS you expect, or something < 2.3.0?

**Comment by heobu** [comment]
Our versions must be much more recent, currently using master branch but we cloned it like a month ago anyway. So that patch is already in. Are we supposed to install something separately for ESAPI or FAPI?

**Comment by williamcroberts** [comment]
> Our versions must be much more recent, currently using master branch but we cloned it like a month ago anyway. So that patch is already in. Are we supposed to install something separately for ESAPI or FAPI?

That's the tpm2-tss project. I really have no idea here. The only other bug report of this failing is coming from a bug in tpm2-tss.... 

The only other thing I can suggest is running it through strace and make sure it's opening the sqlite3 db you expect. Do you have TPM2_PKCS11_STORE exported to point to the store you want? Sometimes the auto-search and work behavior can lead to some odd results.

**Comment by williamcroberts** [comment]
Closing as this is Stale, let me know if anything is currently still broken for you.

**Comment by ikapelyukhin** [comment]
I've ran into this issue as well while using the FIPS-enabled version of OpenSSL on Ubuntu 20.04. Updating `tpm2-tss` to v3.2.0 solved it for me, bisecting has shown that it was fixed in https://github.com/tpm2-software/tpm2-tss/commit/362fda1daa398da2944e76013c215500761d46a5. HTH.

**Comment by vietdang** [comment]
Hello,

I'm facing this issue with the version 3.2.0 on RPi

    tpm2-tss 3.2.0
    esys:               yes
    fapi:               yes
    tctidefaultmodule:  libtss2-tcti-default.so
    tctidefaultconfig:  
    unit:               yes
    integration:        yes
    testing backend:    device
    fuzzing:            none
    debug:              no
    maxloglevel:        trace
    doxygen:            0 
    crypto backend:     ossl
    sysconfdir:         ${prefix}/etc
    localstatedir:      ${prefix}/var
    runstatedir:        ${localstatedir}/run
    sysusersdir:        ${prefix}/etc/sysusers.d
    tmpfilesdir:        ${prefix}/etc/tmpfiles.d
    userstatedir:       $HOME/.local/share
Raspberry Pi 4B
```
cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
```
[INFO] creating a new token
WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x000002c4) 
ERROR: Esys_StartAuthSession: tpm:parameter(2):value is out of range or is not correct for the context
ERROR: Could not create SO seal object
ERROR: Could not create new token
PKCS11_init_token returned -1
```

It's failed at the function Esys_StartAuthSession. tpm2-pkcs11 is the latest master
image
![image](https://user-images.githubusercontent.com/8669903/183538560-800fed18-98c4-4e89-b46a-a9504cb07014.png)


Could advise me.

**Comment by williamcroberts** [comment]
I wish I knew, does it work on your system if you run it against a simulator?

**Comment by vietdang** [comment]
I'm able to create a new token via tpm2_ptool but I'm programming C language with libp11:
```
    pkcs11_ctx = PKCS11_CTX_new();
    // Load the module
    if ((ret = PKCS11_CTX_load(pkcs11_ctx, param->so_path)) != 0) {
        log_error(("PKCS11_CTX_load returned %d", ret));
        PKCS11_CTX_free(pkcs11_ctx);
        return 0;
    }
    // Enumerate the slots
    if ((ret = PKCS11_enumerate_slots(pkcs11_ctx, &slot_list, &slot_count)) != 0) {
        log_error(("PKCS11_CTX_load returned %d", ret));
        goto ERROR;
    }

    // Get the 1st slot with a token
    slot = PKCS11_find_token(pkcs11_ctx, slot_list, slot_count);
    // Find the slot that has a token matching the token_label
    while (slot != NULL)
    {
        if(strlen(slot->token->label) > 0)
        {
            if(strncmp(slot->token->label, param->token_label, strlen(slot->token->label)) == 0)
            {
                break;
            }
        }
        slot = PKCS11_find_next_token(pkcs11_ctx, slot_list, slot_count, slot);
    }
    if (NULL == slot)
    {
        // Initially, there will be uninitialized slot 0. So we utilize it
        slot = PKCS11_find_token(pkcs11_ctx, slot_list, slot_count);
        rand_string(slot, security_officer_pin, PIN_SIZE);

        while (slot != NULL) {
            if (!slot->token->initialized)
                break;
            slot = PKCS11_find_next_token(pkcs11_ctx, slot_list, slot_count, slot);
        }

        log_info(("No token with label : %s, creating a new token", param->token_label));

        if(!slot) {
            log_error(("Slot is NULL"));
            goto ERROR;
        }

        if ((ret = PKCS11_init_token(slot->token, security_officer_pin, param->token_label)) != 0) {
            log_error(("PKCS11_init_token returned %d", ret));
            goto ERROR;
        }
        ...
    }
```

Currently, it always throws the issue from the function `PKCS11_init_token`
```
WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x000002c4) 
ERROR: Esys_StartAuthSession: tpm:parameter(2):value is out of range or is not correct for the context
ERROR: Could not create SO seal object
ERROR: Could not create new token
PKCS11_init_token returned -1
```

If I use tpm2_ptool to create a token, my app can read/write keys to that token. There is only an issue when creating a new token.

**Comment by williamcroberts** [comment]
Can you run command `tpm2_getcap properties-fixed` and post the output?

**Comment by vietdang** [comment]
Hi @williamcroberts 

Here is output

```
TPM2_PT_FAMILY_INDICATOR:
  raw: 0x322E3000
  value: "2.0"
TPM2_PT_LEVEL:
  raw: 0
TPM2_PT_REVISION:
  raw: 0x8A
  value: 1.38
TPM2_PT_DAY_OF_YEAR:
  raw: 0x8
TPM2_PT_YEAR:
  raw: 0x7E2
TPM2_PT_MANUFACTURER:
  raw: 0x49465800
  value: "IFX"
TPM2_PT_VENDOR_STRING_1:
  raw: 0x534C4239
  value: "SLB9"
TPM2_PT_VENDOR_STRING_2:
  raw: 0x36373000
  value: "670"
TPM2_PT_VENDOR_STRING_3:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_4:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_TPM_TYPE:
  raw: 0x0
TPM2_PT_FIRMWARE_VERSION_1:
  raw: 0x70055
TPM2_PT_FIRMWARE_VERSION_2:
  raw: 0x11CB00
TPM2_PT_INPUT_BUFFER:
  raw: 0x400
TPM2_PT_HR_TRANSIENT_MIN:
  raw: 0x4
TPM2_PT_HR_PERSISTENT_MIN:
  raw: 0x7
TPM2_PT_HR_LOADED_MIN:
  raw: 0x3
TPM2_PT_ACTIVE_SESSIONS_MAX:
  raw: 0x40
TPM2_PT_PCR_COUNT:
  raw: 0x18
TPM2_PT_PCR_SELECT_MIN:
  raw: 0x3
TPM2_PT_CONTEXT_GAP_MAX:
  raw: 0xFFFFFFFF
TPM2_PT_NV_COUNTERS_MAX:
  raw: 0x8
TPM2_PT_NV_INDEX_MAX:
  raw: 0x800
TPM2_PT_MEMORY:
  raw: 0x6
TPM2_PT_CLOCK_UPDATE:
  raw: 0x4000
TPM2_PT_CONTEXT_HASH:
  raw: 0xB
TPM2_PT_CONTEXT_SYM:
  raw: 0x6
TPM2_PT_CONTEXT_SYM_SIZE:
  raw: 0x80
TPM2_PT_ORDERLY_COUNT:
  raw: 0xFF
TPM2_PT_MAX_COMMAND_SIZE:
  raw: 0x58C
TPM2_PT_MAX_RESPONSE_SIZE:
  raw: 0x58C
TPM2_PT_MAX_DIGEST:
  raw: 0x20
TPM2_PT_MAX_OBJECT_CONTEXT:
  raw: 0x38F
TPM2_PT_MAX_SESSION_CONTEXT:
  raw: 0x1EE
TPM2_PT_PS_FAMILY_INDICATOR:
  raw: 0x1
TPM2_PT_PS_LEVEL:
  raw: 0x0
TPM2_PT_PS_REVISION:
  raw: 0x103
TPM2_PT_PS_DAY_OF_YEAR:
  raw: 0x0
TPM2_PT_PS_YEAR:
  raw: 0x0
TPM2_PT_SPLIT_MAX:
  raw: 0x80
TPM2_PT_TOTAL_COMMANDS:
  raw: 0x61
TPM2_PT_LIBRARY_COMMANDS:
  raw: 0x60
TPM2_PT_VENDOR_COMMANDS:
  raw: 0x1
TPM2_PT_NV_BUFFER_MAX:
  raw: 0x300
TPM2_PT_MODES:
  raw: 0x1
  value: TPMA_MODES_FIPS_140_2
```
